services:
  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Admin1234!
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  #portainer:
  #  container_name: portainer
  #  restart: always
  #  ports:
  #    - "8080:8000"
  #    - "9000:9000"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "Admin1234!"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
        - "5672:5672"
        - "15672:15672"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discount.grpc:8080"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Admin1234!;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8002:8080"

  discount.grpc:
    container_name: discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Admin1234!;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - discountdb
    ports:
      - "8003:8080"

  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Admin1234!;TrustServerCertificate=True"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - orderdb
        - rabbitmq
    ports:
      - "8004:8080"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - catalog.api
        - basket.api
        - discount.api
        - ordering.api
    ports:
      - "8010:8080"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:CatalogUrl=http://catalog.api:8080"
      - "ApiSettings:BasketUrl=http://basket.api:8080"
      - "ApiSettings:OrderingUrl=http://ordering.api:8080"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
        - catalog.api
        - basket.api
        - ordering.api
    ports:
      - "8005:8080"

  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:GatewayAddress=http://ocelotapigw:8080"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
      - ocelotapigw
      - catalog.api
      - basket.api
      - discount.api
      - ordering.api
    ports:
      - "8006:8080"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data/

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  webstatus:
    container_name: webstatus
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - HealthChecks-UI__HealthChecks:0:Name=Catalog Health Check
      - HealthChecks-UI__HealthChecks:0:Uri=http://catalog.api:8080/health
      - HealthChecks-UI__HealthChecks:1:Name=Basket Health Check
      - HealthChecks-UI__HealthChecks:1:Uri=http://basket.api:8080/health
      - HealthChecks-UI__HealthChecks:2:Name=Discount Health Check
      - HealthChecks-UI__HealthChecks:2:Uri=http://discount.api:8080/health
      - HealthChecks-UI__HealthChecks:3:Name=Discount gRPC Health Check
      - HealthChecks-UI__HealthChecks:3:Uri=http://discount.grpc:8080/health
      - HealthChecks-UI__HealthChecks:4:Name=Ordering Health Check
      - HealthChecks-UI__HealthChecks:4:Uri=http://ordering.api:8080/health
      - HealthChecks-UI__HealthChecks:5:Name=Shopping Aggregator Health Check
      - HealthChecks-UI__HealthChecks:5:Uri=http://shopping.aggregator:8080/health
      - HealthChecks-UI__HealthChecks:6:Name=Web App Health Check
      - HealthChecks-UI__HealthChecks:6:Uri=http://aspnetrunbasics:8080/health
    ports:
      - "8007:8080"
